version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: $PG_USER
          POSTGRES_DB: $PG_DB

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
