version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: circleci/mysql:5.7.26
        environment:
          MYSQL_ROOT_PASSWORD: root_pw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Run Tests & Get Coverage
          command: |
            ./cc-test-reporter before-build
            yarn test --coverage
            ./cc-test-reporter after-build --coverage-input-type lcov

  deploy_dev:
    docker:
      - image: buildpack-deps:xenial
    steps:
      - checkout
      - run:
          name: Deploy Develop to Heroku
          command: | 
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$DEV_APP_NAME.git develop:master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only: develop
